chart/urls.py
from django.conf.urls import url
from . import views


app_name="chart"

urlpatterns=[
    url(r'^$',views.lineChart,name="line"),
    url(r'^ajax/$',views.ajax,name="ajax"),

    url(r'^bar/$',views.barChart,name="pie"),
    url(r'^ajax/$',views.ajax,name="ajax"),
]

graphique/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chart/',include("chart.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chart/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    student_name=models.CharField(max_length=50)
    maths_mark=models.FloatField()
    physics_mark=models.FloatField()
    grammer_mark=models.FloatField()

    def __str__(self):
        return self.student_name

chart/views.py
from django.shortcuts import render
from .models import *
from django.core import serializers
from django.http import HttpResponse
# Create your views here.
def lineChart(request):
    return render(request,'chart/line.html')


def barChart(request):
    return render(request,'chart/bar.html')

def ajax(request):
    student=Student.objects.all()
    data=serializers.serialize('json',student,fields=('student_name','maths_mark','physics_mark','grammer_mark'))
    return HttpResponse(data,content_type='application/json')

chart/templates/chart/bar.html
<!doctype html>
<html>
  <head>
    <title>Bar Chart</title>
    <meta charset="utf-8" />
  </head>
  <body>
  <div style="width:400px;">
      <canvas id="lineChart" height="700" width="700">
    </div>
    </canvas>
    <button id="charge">Charge</charge>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'chart/js/jquery-1.9.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'chart/js/chart.min.js' %}"></script>
    <script>
    $(function(){
      $.ajax({
        url:"{% url 'chart:ajax' %}",
        type:"get",
        success:function(data)
        {
           var student=[];
          var math=[];
          var physics=[];
          var grammer=[];
          for(var i=0;i<data.length;i++)
           {
              student.push(data[i].fields.student_name);
              math.push(data[i].fields.maths_mark);
              physics.push(data[i].fields.physics_mark);
              grammer.push(data[i].fields.grammer_mark);
           }

          const CHART=document.getElementById("lineChart");
        //Voir les proprietes
          console.log(Chart.defaults.global);
          Chart.defaults.global.responsive=true;
        // Chart.defaults.global.data.display=false;
          Chart.defaults.scale.ticks.beginAtZero=true;
          let barChart=new Chart(CHART,
            {
                // type:'doughnut',
                // type:'pie',
                type:'bar',
                data:{
                  labels:student,
                  datasets:[
                    {
                    label:'Math',
                    backgroundColor:'rgba(59,89,152,0.75)',
                    borderColor:'rgba(59,89,152,1)',
                    pointHoverBackgroundColor:'rgba(59,89,152,1)',
                    pointHoverBorderColor:'rgba(59,89,152,1)',
                    data:math
                  },
                  {
                    label:'Physics',
                    backgroundColor:'rgba(29,202,255,0.75)',
                    borderColor:'rgba(29,202,255,1)',
                    pointHoverBackgroundColor:'rgba(29,202,255,1)',
                    pointHoverBorderColor:'rgba(29,202,255,1)',
                    data:physics
                  },
                  {
                    label:'Grammer',
                    backgroundColor:'rgba(211,72,54,0.75)',
                    borderColor:'rgba(211,72,54,1)',
                    pointHoverBackgroundColor:'rgba(211,72,54,1)',
                    pointHoverBorderColor:'rgba(211,72,54,1)',
                    data:grammer
                  },
                ],
                }
            });


        }
      });

    });





    </script>
  </body>
</html>

chart/templates/chart/base.html
<!doctype html>
<html>
  <head>
    <title>{% block titre %}{% endblock  %}</title>
    {% load staticfiles %}
    
    <script type="text/javascript" src="{% static 'chart/js/jquery-1.9.1.min.js' %}"></script>
    <meta charset="utf-8" />
  </head>
  <body>
  <!--  <div style="width:400px;"> -->
      <canvas id="lineChart" height="400" width="400">
    <!-- </div> -->
    </canvas>
    {% block script %}{% endblock  %}
  </body>
</html>

chart/templates/chart/line.html
<!doctype html>
<html>
  <head>
    <title>Line Chart</title>
    <meta charset="utf-8" />
  </head>
  <body>
  <div style="width:400px;">
      <canvas id="lineChart" height="700" width="700">
    </div>
    </canvas>
    <button id="charge">Charge</charge>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'chart/js/jquery-1.9.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'chart/js/chart.min.js' %}"></script>
    <script>
    $(function(){
      $.ajax({
        url:"{% url 'chart:ajax' %}",
        type:"get",
        success:function(data)
        {
          var student=[];
          var math=[];
          var physics=[];
          var grammer=[];
          for(var i=0;i<data.length;i++)
           {
              student.push(data[i].fields.student_name);
              math.push(data[i].fields.maths_mark);
              physics.push(data[i].fields.physics_mark);
              grammer.push(data[i].fields.grammer_mark);
           }

          const CHART=document.getElementById("lineChart");
        //Voir les proprietes
          console.log(Chart.defaults.global);
          Chart.defaults.global.responsive=true;
        // Chart.defaults.global.data.display=false;
          Chart.defaults.scale.ticks.beginAtZero=true;
          let barChart=new Chart(CHART,
            {
                // type:'doughnut',
                // type:'pie',
                type:'line',
                data:{
                  labels:student,
                  datasets:[
                    {
                    label:'Math',
{#                    backgroundColor:'rgba(59,89,152,0.75)',#}
                    borderColor:'rgba(59,89,152,1)',
                    lineTension:0,
                    pointHoverBackgroundColor:'rgba(59,89,152,1)',
                    pointHoverBorderColor:'rgba(59,89,152,1)',
                    data:math
                  },
                  {
                    label:'Physics',
{#                    backgroundColor:'rgba(29,202,255,0.75)',#}
                    borderColor:'rgba(29,202,255,1)',
                      lineTension:0,
                    pointHoverBackgroundColor:'rgba(29,202,255,1)',
                    pointHoverBorderColor:'rgba(29,202,255,1)',
                    data:physics
                  },
                  {
                    label:'Grammer',
{#                    backgroundColor:'rgba(211,72,54,0.75)',#}
                    borderColor:'rgba(211,72,54,1)',
                      lineTension:0,
                    pointHoverBackgroundColor:'rgba(211,72,54,1)',
                    pointHoverBorderColor:'rgba(211,72,54,1)',
                    data:grammer
                  },
                ],
                }
            });

        }
      });

    });





    </script>
  </body>
</html>

chart/templates/chart/line.toto.html
{% extends "chart/base.html" %}
{% block titre %}Nombre des followers{% endblock  %}
{% block script %}
<button id="btn">Ca ici</button>
<script type="text/javascript" src="/static/chart/js/chart.min.js"></script>
<script type="text/javascript" src="/static/chart/js/line.js"></script>
{% endblock  %}